"""initial schema

Revision ID: a54664718ec8
Revises: 
Create Date: 2026-08-28 00:08:44.956080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54664718ec8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_units', sa.Integer(), nullable=False),
    sa.Column('output_units', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_job_id'), 'ai_usage', ['job_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_operation'), 'ai_usage', ['operation'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('processing_status', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_category'), 'images', ['category'], unique=False)
    op.create_index(op.f('ix_images_processing_status'), 'images', ['processing_status'], unique=False)
    op.create_index(op.f('ix_images_subject'), 'images', ['subject'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_category'), 'posts', ['category'], unique=False)
    op.create_table('image_embeddings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_embeddings_image_id'), 'image_embeddings', ['image_id'], unique=False)
    op.create_table('post_embeddings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('post_id', sa.String(length=32), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_embeddings_post_id'), 'post_embeddings', ['post_id'], unique=False)
    op.create_table('suggestions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('post_id', sa.String(length=32), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('guard_decision', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggestions_guard_decision'), 'suggestions', ['guard_decision'], unique=False)
    op.create_index(op.f('ix_suggestions_image_id'), 'suggestions', ['image_id'], unique=False)
    op.create_index(op.f('ix_suggestions_post_id'), 'suggestions', ['post_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('suggestion_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_suggestion_id'), 'reviews', ['suggestion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_suggestion_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_suggestions_post_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_image_id'), table_name='suggestions')
    op.drop_index(op.f('ix_suggestions_guard_decision'), table_name='suggestions')
    op.drop_table('suggestions')
    op.drop_index(op.f('ix_post_embeddings_post_id'), table_name='post_embeddings')
    op.drop_table('post_embeddings')
    op.drop_index(op.f('ix_image_embeddings_image_id'), table_name='image_embeddings')
    op.drop_table('image_embeddings')
    op.drop_index(op.f('ix_posts_category'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_images_subject'), table_name='images')
    op.drop_index(op.f('ix_images_processing_status'), table_name='images')
    op.drop_index(op.f('ix_images_category'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_ai_usage_operation'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_job_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
